name: Epic
description: Criar uma funcionalidade ampla do sistema
title: "[EPIC] Nome da funcionalidade"
labels: [epic]
body:
  - type: markdown
    attributes:
      value: "## Descrição do Epic"
  - type: textarea
    id: description
    attributes:
      label: Descrição
      placeholder: Descreva o escopo geral deste Epic
  - type: textarea
    id: user_stories
    attributes:
      label: User Stories Relacionadas
      placeholder: Liste as histórias de usuário que compõem este Epic