name: User Story
description: Criar uma história de usuário do sistema
title: "[USER STORY] Nome da funcionalidade"
labels: [user story]
body:
  - type: markdown
    attributes:
      value: "## Formato recomendado: Como [usuário], quero [ação] para [objetivo]"
  - type: input
    id: role
    attributes:
      label: Quem está pedindo? (Usuário)
      placeholder: "Ex: agente, agente-chefe"
  - type: textarea
    id: goal
    attributes:
      label: O que deseja fazer?
      placeholder: "Ex: cadastrar uma residência"
  - type: textarea
    id: reason
    attributes:
      label: Por que essa funcionalidade é importante?
      placeholder: "Ex: para poder realizar pesquisas posteriormente"
  - type: textarea
    id: context
    attributes:
      label: Contexto técnico?
      placeholder: "Ex: Esse item deve ser criado uma tela com o nome..."
  - type: checkboxes
    id: tags
    attributes:
      label: Quais áreas estão envolvidas?
      options:
        - label: Front-end
        - label: Back-end
        - label: Banco de Dados
        - label: Documentação
